### ISSUE TITLE
Can not get tweet with Age-restricted  content

### ISSUE THREAD

**Issue by xtclh** [inteoryx/twitter-video-dl#11]
Try this url: https://twitter.com/TheDeadDistrict/status/1551472547149058050
It can not return the content of this tweet.
Just return:
Age-restricted adult content. This content may not be suitable for users under the age of 18. To view this media, you need to be logged into Twitter. understand more

**Comment by inteoryx** [comment]
I don't think this is possible.  Just looking at it a little bit, it doesn't seem like twitter lets the unauthenticated user view this content.  If you can see this video without logging in, e.g. if you can visit it in incognito and get the video to play without signing in, then please reopen this with a description of how.  Otherwise, I don't think this is possible.  Sorry!
