### ISSUE TITLE
add login features  

### ISSUE THREAD

**Issue by zhaoxiaohai** [inteoryx/twitter-video-dl#14]
some videos need login to download

**Comment by inteoryx** [comment]
Do you have an example of one?

**Comment by zhaoxiaohai** [comment]
<img width="591" alt="image" src="https://user-images.githubusercontent.com/33596802/228682800-ff51cd5e-de23-48ca-a794-e09f0f38836e.png">


you can search some Age-restricted  video. I don't want to post the link.

**Comment by moo611** [comment]
> If a particular video doesn't work please provide the URL to that video. I'm not going to guess what content you're trying to download that doesn't work. If you have a link feel free to reopen.

Here is one:
https://twitter.com/babyts520/status/1648631875672612864

**Comment by inteoryx** [comment]
Thanks for providing a URL (NSFW obviously).  I took a look at this and it doesn't seem possible to get the video unauthenticated.  The request to get the container file requires a valid auth_token.  To get a valid auth_token we would need to login.

I can imagine two potential solutions.

1. A "dummy" account for the script.  We could create a twitter account to be used by the script.  We would need to lock it down somehow so people couldn't change the password or tweet from the account to prevent the account becoming unusable/banned.  I'm not sure if it is possible to create a locked down account like this.
2. Ask the user for their credentials.  I'm hesitant to go this route because it would mean asking the user to type in their username and password.  That seems insecure.  It's possible there is some kind of OAuth solution to this, but I don't really want to figure that out.

Ultimately, I think the easiest thing is just not to support videos that you can't see unauthenticated.  If you submit a PR solving this problem I will consider it.
