### ISSUE TITLE
Could not find any mp4s to download.  Make sure you are using the correct url.  If you are, then file a GitHub issue and copy and paste this message.  Tweet url: https://twitter.com/gujarat_titans/status/1655207515162832897

### ISSUE THREAD

**Issue by shikhar-newzera** [inteoryx/twitter-video-dl#22]
Could not find any mp4s to download.  Make sure you are using the correct url.  If you are, then file a GitHub issue and copy and paste this message.  Tweet url: https://twitter.com/gujarat_titans/status/1655207515162832897

**Comment by inteoryx** [comment]
Should be fixed with most recent change.  Please pull the latest and try again.

Seems the issue was that there is an additional pattern for really short videos like these.  This video is maybe a glorified gif turned mp4?  No idea how long this existed or if it is new behavior from twitter.

Added this video to the tests too to make sure we continue supporting it in future.

Thank you for reporting this issue.

**Comment by mustlezoo** [comment]
But nsfw video seems can not view in guest mode
