### ISSUE TITLE
Did not find container URLs

### ISSUE THREAD

**Issue by euMts** [inteoryx/twitter-video-dl#5]
Today I got this error while downloading a video:
AssertionError: Did not find container URLs.

Video-url:
https://twitter.com/nargas_coringa/status/1492546170895355912

**Comment by inteoryx** [comment]
@euMts Thanks for the report.  Just pushed a change that should fix this.  Please pull the latest and confirm that it works for you, I was able to reproduce the original issue and successfully download the video after my fix.

Seems the issue was that when videos are very short twitter does not have a separate container, but rather just a single mp4 file.  The script handles that case now.

If this is still broken for you please reopen with an explanation - thanks!

**Comment by euMts** [comment]
It worked! good job mate!
I used your repo in my latest project, come take a look!
(obs. Of course I added your github url as a comment, and I made it explicit that the code is YOURS)
